using PlatformOpsHub.Integrations.Interfaces;

namespace PlatformOpsHub.Integrations.Mock;

public class MockAzureOpenAIClient : IAzureOpenAIClient
{
    public Task<string> GenerateNewsletterAsync(string period, DateTime rangeStart, DateTime rangeEnd, string dataContext)
    {
        var markdown = $@"# PlatformOps {period} Newsletter
**Period:** {rangeStart:dd MMM yyyy} - {rangeEnd:dd MMM yyyy}

## 🎯 Key Achievements

### Service Team
- ✅ Nightly regression stability improved to 92% (target: 95%)
- ✅ Successfully deployed 3 releases to production with zero rollbacks
- ✅ Reduced average build time by 15% through pipeline optimization

### Change Team
- 💰 **Cost Optimization:** Achieved £27.5K savings this month (YTD: £165K vs £350K target)
- 🚀 Implemented auto-shutdown for non-prod resources
- 📊 Right-sized 12 over-provisioned Azure VMs

### DBA Team
- ⚡ Optimized 5 slow queries, improving response time by 40%
- 🔧 Completed index maintenance on production databases
- 📈 Database growth tracking dashboard launched

## 📊 Metrics Snapshot

| KPI | This {period} | Previous | Trend |
|-----|---------------|----------|-------|
| Build Time (avg) | 8.2 min | 9.7 min | ⬇️ 15% |
| Time to Release | 4.3 days | 5.1 days | ⬇️ 16% |
| MTTR | 2.1 hours | 2.8 hours | ⬇️ 25% |
| Change Failure Rate | 8% | 12% | ⬇️ 33% |
| Code Coverage | 76.8% | 74.2% | ⬆️ 3.5% |

## 🔒 Security & Quality

- **SonarQube:** Reduced bugs from 15 to 10, vulnerabilities from 8 to 4
- **Checkmarx:** Critical vulnerabilities down from 5 to 2
- **Code Smells:** Decreased by 12% week-on-week

## 🎓 Learning & Growth

- 🏆 **Top Learner:** Sarah Johnson (450 points)
- 📚 3 team members completed Azure DevOps 101
- ✅ 12 quiz attempts with 83% pass rate

## 🎉 Celebrations

- 🎂 Happy Birthday to Alex Chen and Maria Garcia!
- 🎊 Work Anniversary: John Smith (3 years with PlatformOps)

## 🚀 Next {period} Focus

1. **Service:** Achieve 95% regression stability target
2. **Change:** Continue cost optimization initiatives (target: £29K/month)
3. **DBA:** Complete query tuning backlog (5 remaining)

---
*Generated by PlatformOps Hub AI Assistant*
";

        return Task.FromResult(markdown);
    }

    public Task<string> GetInsightAsync(string question, string context)
    {
        var insights = new Dictionary<string, string>
        {
            ["risk"] = "⚠️ **Top Risks:**\n- Regression stability at 92% (below 95% target)\n- Cost trending slightly above monthly target in last 2 weeks\n- 2 critical Checkmarx vulnerabilities still open",
            ["improvement"] = "📈 **Top Improvements:**\n- Build time reduced by 15% through caching optimization\n- MTTR improved by 25% with better monitoring\n- Code coverage increased to 76.8%",
            ["cost"] = "💰 **Cost Analysis:**\n- YTD: £165K saved vs £350K annual target (47% progress)\n- On track to meet annual goal\n- Auto-shutdown initiative saving £5K/month\n- Recommend: review storage costs (trending up)",
            ["quality"] = "🔍 **Code Quality:**\n- Positive trend: bugs ⬇️33%, vulnerabilities ⬇️50%\n- Coverage improving steadily (+3.5% this period)\n- Focus needed: 2 critical Checkmarx issues in platform-web"
        };

        var lowerQuestion = question.ToLower();
        foreach (var (key, value) in insights)
        {
            if (lowerQuestion.Contains(key))
            {
                return Task.FromResult(value);
            }
        }

        return Task.FromResult("💡 **General Insight:**\nOverall progress is strong across all teams. Key focus areas: regression stability, cost optimization, and critical security vulnerabilities.");
    }
}

public class MockTeamsNotificationClient : ITeamsNotificationClient
{
    public Task SendNotificationAsync(string webhookUrl, string adaptiveCardJson)
    {
        Console.WriteLine($"[MOCK] Sending Teams notification to {webhookUrl}");
        Console.WriteLine($"[MOCK] Card: {adaptiveCardJson[..Math.Min(100, adaptiveCardJson.Length)]}...");
        return Task.CompletedTask;
    }

    public Task SendBirthdayNotificationAsync(string displayName, string email)
    {
        Console.WriteLine($"[MOCK] Sending birthday notification to {displayName} ({email})");
        return Task.CompletedTask;
    }

    public Task SendAnniversaryNotificationAsync(string displayName, int years)
    {
        Console.WriteLine($"[MOCK] Sending {years}-year anniversary notification to {displayName}");
        return Task.CompletedTask;
    }

    public Task SendNewsletterNotificationAsync(string title, string url)
    {
        Console.WriteLine($"[MOCK] Sending newsletter notification: {title}");
        return Task.CompletedTask;
    }
}

public class MockAzureDevOpsClient : IAzureDevOpsClient
{
    public Task<List<PipelineBuildDto>> GetRecentBuildsAsync(int days = 7)
    {
        var builds = new List<PipelineBuildDto>();
        var random = new Random();

        for (int i = 0; i < 20; i++)
        {
            var queuedAt = DateTime.UtcNow.AddDays(-random.Next(0, days));
            var duration = 300 + random.Next(-120, 300);
            var status = random.Next(100) < 85 ? "Succeeded" : "Failed";

            builds.Add(new PipelineBuildDto(
                $"Platform-API-CI",
                $"Build-{20240000 + i}",
                status,
                queuedAt,
                queuedAt.AddSeconds(duration),
                duration
            ));
        }

        return Task.FromResult(builds);
    }

    public Task<List<ReleaseDto>> GetRecentReleasesAsync(int days = 7)
    {
        var releases = new List<ReleaseDto>
        {
            new("Release-2026-003", "R-003", "Prod", "Succeeded", DateTime.UtcNow.AddDays(-3)),
            new("Release-2026-002", "R-002", "Staging", "Succeeded", DateTime.UtcNow.AddDays(-5)),
            new("Release-2026-002", "R-002", "Dev", "Failed", DateTime.UtcNow.AddDays(-6)),
            new("Release-2026-001", "R-001", "Prod", "Succeeded", DateTime.UtcNow.AddDays(-10))
        };

        return Task.FromResult(releases);
    }

    public Task<List<PullRequestDto>> GetRecentPullRequestsAsync(int days = 7)
    {
        var prs = new List<PullRequestDto>
        {
            new("Add user authentication", "john.smith@company.com", "Completed", DateTime.UtcNow.AddDays(-2), 5),
            new("Fix regression test flakiness", "sarah.johnson@company.com", "Active", DateTime.UtcNow.AddDays(-1), 3),
            new("Optimize database queries", "alex.chen@company.com", "Completed", DateTime.UtcNow.AddDays(-4), 8)
        };

        return Task.FromResult(prs);
    }
}

public class MockJiraClient : IJiraClient
{
    public Task<List<JiraIssueDto>> GetIssuesByProjectAsync(string projectKey)
    {
        var issues = new List<JiraIssueDto>
        {
            new("PLAT-101", "Implement cost optimization dashboard", "In Progress", "Story", "maria.garcia@company.com"),
            new("PLAT-102", "Database performance tuning", "To Do", "Task", "alex.chen@company.com"),
            new("PLAT-103", "Fix nightly regression failures", "Done", "Bug", "sarah.johnson@company.com")
        };

        return Task.FromResult(issues);
    }

    public Task<JiraIssueDto?> GetIssueByKeyAsync(string issueKey)
    {
        return Task.FromResult<JiraIssueDto?>(
            new JiraIssueDto(issueKey, "Sample Jira Issue", "In Progress", "Story", "user@company.com")
        );
    }
}

public class MockAzureCostClient : IAzureCostClient
{
    public Task<List<CostDataDto>> GetCostDataAsync(DateTime startDate, DateTime endDate, string scope)
    {
        var costs = new List<CostDataDto>();
        var random = new Random();

        for (var date = startDate; date <= endDate; date = date.AddDays(1))
        {
            var dailyCost = 900m + (decimal)(random.NextDouble() * 200); // £900-£1100/day
            costs.Add(new CostDataDto(date, scope, dailyCost, "GBP"));
        }

        return Task.FromResult(costs);
    }
}

public class MockSonarQubeClient : ISonarQubeClient
{
    public Task<SonarMetricsDto> GetProjectMetricsAsync(string projectKey)
    {
        var random = new Random();
        return Task.FromResult(new SonarMetricsDto(
            projectKey,
            Bugs: 8 + random.Next(0, 10),
            Vulnerabilities: 3 + random.Next(0, 8),
            CodeSmells: 100 + random.Next(0, 50),
            Coverage: 70m + (decimal)(random.NextDouble() * 15),
            Criticals: random.Next(0, 3),
            Highs: 3 + random.Next(0, 5),
            Mediums: 5 + random.Next(0, 10),
            Lows: 10 + random.Next(0, 15)
        ));
    }

    public Task<List<SonarProjectDto>> GetAllProjectsAsync()
    {
        var projects = new List<SonarProjectDto>
        {
            new("platform-api", "Platform API"),
            new("platform-web", "Platform Web"),
            new("platform-worker", "Platform Worker")
        };

        return Task.FromResult(projects);
    }
}

public class MockCheckmarxClient : ICheckmarxClient
{
    public Task<CheckmarxScanDto> GetLatestScanAsync(string projectName)
    {
        var random = new Random();
        return Task.FromResult(new CheckmarxScanDto(
            projectName,
            DateTime.UtcNow.AddDays(-random.Next(1, 7)),
            TotalVulnerabilities: 10 + random.Next(0, 20),
            Criticals: random.Next(0, 5),
            Highs: 3 + random.Next(0, 8),
            Mediums: 5 + random.Next(0, 10),
            Lows: 2 + random.Next(0, 5)
        ));
    }

    public Task<List<CheckmarxProjectDto>> GetAllProjectsAsync()
    {
        var projects = new List<CheckmarxProjectDto>
        {
            new("Platform API", "proj-001"),
            new("Platform Web", "proj-002"),
            new("Platform Worker", "proj-003")
        };

        return Task.FromResult(projects);
    }
}
